# Generated by Django 6.0.2 on 2026-02-23 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Marker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=250)),
                ('location', models.CharField(max_length=100)),
                ('commemorated_year', models.IntegerField()),
                ('inscription', models.TextField(max_length=1000)),
            ],
        ),
    ]
